runtime: nodejs18
handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
    secure: always
  # Catch all handler to index.html
  - url: /.*
    secure: always
    static_files: build/index.html
    upload: build/index.html